version: "3"

services:
  server:
    build: server/
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build: client/
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: "mongo-db"